version: "3.9" 
services:
  db:
    image: mongo
    container_name: dbmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: So1pass_2022
    ports:
      - "4000:27017"
    restart: always
    volumes:
      - /home/angel/Documentos/Proyectos/Sopes1/[SO1]Practica1_201901816/dockerVolumen:/data/db
    networks:
      - practica1-net

  backend:
    build: ./backend
    container_name: backend_p1
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: So1pass_2022
      MONGO_HOST: 192.168.15.141:4000
    ports:
    - "5000:5000"
    restart: always
    depends_on:
    - db
    networks:
    - practica1-net

  frontend:
    build: ./frontend
    container_name: frontend_p1
    ports:
    - "3000:3000"
    restart: always
    depends_on:
    - backend
    networks:
    - practica1-net
  
volumes:
  mongodata:

networks:
  practica1-net:
    name: "practica1-net"
    driver: bridge